var myHeading = document.querySelector('h1');
myHeading.innerHTML = 'Cloud Service<br>20180327';
var text = 'This is a text.';
text=10.5;
var a = 33.7;
var b = a*text;
//alert(text);
var iceCream = 'chocolate';
var id = prompt('ID 입력','');
alert(id+'가 로그인함.');